// frontend-vue/src/pages/Main/Main.vue
<script setup>
import Header from '../../components/Header/Header.vue';
import Filter from '../../components/Filter/Filter.vue';
import OfferList from '../../components/OfferList/OfferList.vue';
import './Main.css'

</script>

<template>
  <div>
    <Header/>
    <div class="main-horizontal-container">
      <Filter/>
      <OfferList/>
    </div>
  </div>
</template>

// frontend-react/src/pages/Main/Main.jsx
import React from 'react';
import './Main.css'
import Header from "../../components/Header/Header.jsx";
import Filter from "../../components/Main/Filter/Filter.jsx";
import OfferList from "../../components/Main/OfferList/OfferList.jsx";

function Main() {

    return (
        <div>
            <Header/>
            <div className="main-horizontal-container">
                <Filter/>
                <OfferList/>
            </div>


        </div>
    );
}

export default Main;
