// frontend-vue/src/pages/Book/Book.vue
<script setup>
import { ref, onMounted } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { Checkbox } from 'ant-design-vue'
import dayjs from 'dayjs'
import Header from '../../components/Header/Header.vue'
import api from '../../services/api'
import './Book.css'

const route = useRoute()
const router = useRouter()

const offer = ref(null)

const availableDates = [
  dayjs().startOf('day'),
  dayjs().add(1, 'day').startOf('day'),
  dayjs().add(2, 'day').startOf('day')
]

const availableTimes = ['16:00', '17:00', '18:00']

const selectedDate = ref(null)
const selectedTime = ref(null)

const fmt = (d) => d.format('DD MMMM YYYY')
const fmtRange = (t) => `${t} - ${dayjs(t, 'HH:mm').add(45, 'm').format('HH:mm')}`

const handleConfirm = async () => {
  if (!selectedDate.value || !selectedTime.value) {
    alert('Wybierz datę i godzinę.')
    return
  }
  const [h, m] = selectedTime.value.split(':')
  const appointment = selectedDate.value.hour(+h).minute(+m)

  try {
    await api.post('/appointment', {
      name: 'Jazda próbna',
      status: 'created',
      appointmentDate: appointment.format('YYYY-MM-DDTHH:mm:ss'),
      announcementId: offer.value.id
    })

    await router.push({
      path: `/success/${offer.value.id}`,
      query: { date: appointment.format('DD.MM.YYYY [godz.] HH:mm') }
    })
  } catch {
    alert('Nie udało się umówić wizyty.')
  }
}

const fetchOffer = async () => {
  try {
    const { data } = await api.get(`/announcement/with-images/${route.params.id}`)
    offer.value = data
  } catch {}
}

onMounted(fetchOffer)
</script>

<template>
  <Header />
  <div v-if="offer" class="book-page-container">
    <div class="book-container">
      <p class="book-title">Umów się na jazdę próbną...</p>

      <div class="book-offer-card">
        <div class="book-offer-horizontal-container">
          <img :src="offer.imageUrls?.[0]" alt="">
          <div class="book-offer-vertical-container">
            <h3 class="book-offer-title">{{ offer.name }}</h3>
            <p class="book-offer-location">
              {{ offer.vehicle?.productionYear }} - {{ offer.vehicle?.mileage?.toLocaleString() }} km
            </p>
          </div>
          <p class="book-offer-price">{{ offer.price?.toLocaleString() }} PLN</p>
        </div>
      </div>

      <div class="book-date-horizontal-container">
        <div>
          <p class="book-text">Data:</p>
          <div class="book-checkbox-vertical-container">
            <Checkbox
                v-for="d in availableDates"
                :key="d.valueOf()"
                class="book-checkbox"
                :checked="selectedDate?.isSame(d, 'day')"
                @change="() => (selectedDate = d)"
            >
              {{ fmt(d) }}
            </Checkbox>
          </div>
        </div>

        <div>
          <p class="book-text">Godzina:</p>
          <div class="book-checkbox-vertical-container">
            <Checkbox
                v-for="t in availableTimes"
                :key="t"
                class="book-checkbox"
                :checked="selectedTime === t"
                @change="() => (selectedTime = t)"
            >
              {{ fmtRange(t) }}
            </Checkbox>
          </div>
        </div>
      </div>

      <button class="book-confirm-button" @click="handleConfirm">Potwierdzam</button>
    </div>
  </div>
  <div v-else>Ładowanie danych oferty...</div>
</template>

// frontend-react/src/pages/Book/Book.jsx
import React, { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import './Book.css';
import Header from '../../components/Header/Header.jsx';
import { Checkbox } from 'antd';
import dayjs from 'dayjs';
import { useAuth } from '../../context/AuthContext';
import { useNavigate } from 'react-router-dom';

function Book() {
    const { id } = useParams();
    const { user, api } = useAuth();
    const [offer, setOffer] = useState(null);
    const navigate = useNavigate();

    const [selectedDate, setSelectedDate] = useState(null);
    const [selectedTime, setSelectedTime] = useState(null);

    const availableDates = [
        dayjs().startOf('day'),
        dayjs().add(1, 'day').startOf('day'),
        dayjs().add(2, 'day').startOf('day')
    ];

    const availableTimes = ['16:00', '17:00', '18:00'];

    const handleConfirm = async () => {
        if (!selectedDate || !selectedTime) {
            alert("Wybierz datę i godzinę.");
            return;
        }

        const [hour, minute] = selectedTime.split(':');
        const appointmentDate = selectedDate.hour(Number(hour)).minute(Number(minute));

        try {
            await api.post("/appointment", {
                name: "Jazda próbna",
                status: "created",
                appointmentDate: appointmentDate.format('YYYY-MM-DDTHH:mm:ss'),
                announcementId: offer.id
            });

            navigate(`/success/${offer.id}`, {
                state: {
                    appointmentDate: appointmentDate.format("DD.MM.YYYY [godz.] HH:mm")
                }
            });
        } catch (error) {
            console.error("Błąd podczas umawiania wizyty", error);
            alert("Nie udało się umówić wizyty.");
        }

    };

    useEffect(() => {
        const fetchOffer = async () => {
            try {
                const response = await api.get(`/announcement/with-images/${id}`);
                setOffer(response.data);
            } catch (err) {
                console.error('Błąd pobierania oferty:', err);
            }
        };

        fetchOffer();
    }, [api, id]);

    if (!offer) return <div>Ładowanie danych oferty...</div>;

    return (
        <div>
            <Header />
            <div className="book-page-container">
                <div className="book-container">
                    <p className="book-title">Umów się na jazdę próbną...</p>

                    <div className="book-offer-card">
                        <div className="book-offer-horizontal-container">
                            <img src={offer.imageUrls?.[0]} alt="Zdjęcie pojazdu" />
                            <div className="book-offer-vertical-container">
                                <h3 className="book-offer-title">{offer.name}</h3>
                                <p className="book-offer-location">
                                    {offer.vehicle?.productionYear} – {offer.vehicle?.mileage?.toLocaleString()} km
                                </p>
                            </div>
                            <p className="book-offer-price">
                                {offer.price?.toLocaleString()} PLN
                            </p>
                        </div>
                    </div>

                    <div className="book-date-horizontal-container">
                        <div>
                            <p className="book-text">Data:</p>
                            <div className="book-checkbox-vertical-container">
                                {availableDates.map(date => (
                                    <Checkbox
                                        key={date.format('YYYY-MM-DD')}
                                        className="book-checkbox"
                                        checked={selectedDate?.isSame(date, 'day')}
                                        onChange={() => setSelectedDate(date)}
                                    >
                                        {date.format('DD MMMM YYYY')}
                                    </Checkbox>
                                ))}
                            </div>
                        </div>

                        <div>
                            <p className="book-text">Godzina:</p>
                            <div className="book-checkbox-vertical-container">
                                {availableTimes.map(time => (
                                    <Checkbox
                                        key={time}
                                        className="book-checkbox"
                                        checked={selectedTime === time}
                                        onChange={() => setSelectedTime(time)}
                                    >
                                        {time} - {dayjs(time, 'HH:mm').add(45, 'minute').format('HH:mm')}
                                    </Checkbox>
                                ))}
                            </div>
                        </div>
                    </div>

                    <button className="book-confirm-button" onClick={handleConfirm}>
                        Potwierdzam
                    </button>
                </div>
            </div>
        </div>
    );
}

export default Book;
