// frontend-react/src/components/Header/Header.jsx
import React from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../../context/AuthContext.jsx';
import './Header.css';
import { FiLogOut, FiUser } from "react-icons/fi";

const Header = () => {
    const { user, isAuthenticated, logout } = useAuth();
    const navigate = useNavigate();

    const handleLoginClick = () => {
        navigate('/login');
    };

    const handleRegisterClick = () => {
        navigate('/register');
    };

    const handleMainClick = () => {
        navigate('/main');
    };

    const handleLogout = () => {
        logout();
        navigate('/login');
    };

    const handleProfileClick = () => {
        navigate('/profile');
    };

    return (
        <header className="header">
            <h1 onClick={handleMainClick} className="header-title">AUTO KOMIS</h1>

            {isAuthenticated ? (
                <div className="header-buttons-container">
                    <span className="user-email-display">{user?.email}</span>
                    <button
                        className="icon-button profile-button"
                        onClick={handleProfileClick}
                        aria-label="Profile"
                    >
                        <FiUser className="button-icon" />
                    </button>
                    <button
                        className="icon-button logout-button"
                        onClick={handleLogout}
                        aria-label="Logout"
                    >
                        <FiLogOut className="button-icon" />
                    </button>
                </div>
            ) : (
                <div className="header-nav-buttons">
                    <button
                        className="header-nav-login-button"
                        onClick={handleLoginClick}
                    >
                        Zaloguj
                    </button>
                    <button
                        className="header-nav-register-button"
                        onClick={handleRegisterClick}
                    >
                        Zarejestruj
                    </button>
                </div>
            )}
        </header>
    );
};

export default Header;

// frontend-vue/src/components/Header/Header.vue
<script setup>
import { computed } from 'vue';
import { useRouter } from 'vue-router';
import { useAuthStore } from '../../store/auth';
import './Header.css'


const router = useRouter();
const authStore = useAuthStore();

const isAuthenticated = computed(() => authStore.isAuthenticated);
const user = computed(() => authStore.user);

const handleLoginClick = () => {
  router.push('/login');
};

const handleRegisterClick = () => {
  router.push('/register');
};

const handleMainClick = () => {
  router.push('/main');
};

const handleLogout = async () => {
  await authStore.logout();
  await router.push('/login');
};

const handleProfileClick = () => {
  router.push('/profile');
};
</script>

<template>
  <header class="header">
    <h1 @click="handleMainClick" class="header-title">AUTO KOMIS</h1>

    <div v-if="isAuthenticated" class="header-buttons-container">
      <span class="user-email-display">{{ user?.email }}</span>
      <button
          class="icon-button profile-button"
          @click="handleProfileClick"
          aria-label="Profile"
      >
        <i class="fi fi-user button-icon"></i>
      </button>
      <button
          class="icon-button logout-button"
          @click="handleLogout"
          aria-label="Logout"
      >
        <i class="fi fi-log-out button-icon"></i>
      </button>
    </div>
    <div v-else class="header-nav-buttons">
      <button
          class="header-nav-login-button"
          @click="handleLoginClick"
      >
        Zaloguj
      </button>
      <button
          class="header-nav-register-button"
          @click="handleRegisterClick"
      >
        Zarejestruj
      </button>
    </div>
  </header>
</template>
