// frontend-vue/src/pages/Login/Login.vue
<template>
  <div>
    <div class="login-container">
      <p class="hello-word">Witaj!</p>
      <p class="login-word">Zaloguj się</p>

      <div v-if="error" style="color: red; margin-bottom: 10px;">{{ error }}</div>

      <p class="email-word">E-mail</p>
      <input
          class="email-input-data"
          type="email"
          v-model="email"
      />

      <p class="email-word">Hasło</p>
      <input
          class="password-input-data"
          type="password"
          v-model="password"
      />

      <button
          class="login-button"
          @click="handleLogin"
          :disabled="loading"
      >
        {{ loading ? 'Logowanie...' : 'Zaloguj' }}
      </button>

      <button
          class="nav-register-button"
          @click="navigateToRegister"
      >
        Nie masz konta? Zarejestruj się
      </button>
    </div>
  </div>
</template>

<script>
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { useAuthStore } from '../../store/auth'
import './Login.css'

export default {
  name: 'Login',
  setup() {
    const router = useRouter()
    const authStore = useAuthStore()

    const email = ref('')
    const password = ref('')
    const error = ref('')
    const loading = ref(false)

    const handleLogin = async () => {
      if (!email.value || !password.value) {
        error.value = 'Proszę wypełnić wszystkie pola'
        return
      }

      loading.value = true
      try {
        await authStore.login(email.value, password.value)
      } catch (err) {
        error.value = err.response?.data?.message || 'Błąd logowania'
      } finally {
        loading.value = false
      }
    }

    const navigateToRegister = () => {
      router.push('/register')
    }

    return {
      email,
      password,
      error,
      loading,
      handleLogin,
      navigateToRegister
    }
  }
}
</script>

// frontend-react/src/pages/Login/Login.jsx
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../../context/AuthContext.jsx';
import './Login.css';

function Login() {
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');
    const [loading, setLoading] = useState(false);
    const { login } = useAuth();
    const navigate = useNavigate();

    const handleLogin = async (e) => {
        e.preventDefault();


        setLoading(true);
        try {
            await login(email, password);
            navigate('/main');
        } catch (err) {
            console.log(err.response?.data?.message || 'Błąd logowania')
        } finally {
            setLoading(false);
        }
    };
    const navigateToRegister = () => {
        navigate('/register');
    };



    return (
        <div>
            <div className="login-container">
                <p className="hello-word">Witaj</p>
                <p className="login-word">Zaloguj się</p>
                <p className="email-word">E-mail</p>
                <input
                    className="email-input-data"
                    type="email"
                    value={email}
                    onChange={(e) => setEmail(e.target.value)}
                />

                <p className="email-word">Hasło</p>
                <input
                    className="password-input-data"
                    type="password"
                    value={password}
                    onChange={(e) => setPassword(e.target.value)}
                />


                <button
                    className="register-button"
                    onClick={handleLogin}
                    disabled={loading}
                >
                    {loading ? 'Logowanie...' : 'Zaloguj'}
                </button>
                <button
                    className="nav-register-button"
                    onClick={navigateToRegister}
                >Nie masz konta? Zarejestruj się
                </button>

            </div>


        </div>
    );
}

export default Login;
