// frontend-vue/src/pages/Register/Register.vue
<template>
  <div>
    <div class="register-container">
      <p class="join-word">Dołącz!</p>
      <p class="register-word">Zarejestruj się</p>

      <div v-if="error" style="color: red; margin-bottom: 10px;">{{ error }}</div>

      <p class="email-word">Nazwa użytkownika</p>
      <input
          class="email-input-data"
          type="text"
          v-model="username"
      />

      <p class="email-word">E-mail</p>
      <input
          class="email-input-data"
          type="email"
          v-model="email"
      />

      <p class="email-word">Hasło</p>
      <input
          class="password-input-data"
          type="password"
          v-model="password"
      />

      <p class="email-word">Powtórz hasło</p>
      <input
          class="repeat-password-input-data"
          type="password"
          v-model="confirmPassword"
      />

      <button
          class="register-button"
          @click="handleRegister"
          :disabled="loading"
      >
        {{ loading ? 'Rejestracja...' : 'Zarejestruj' }}
      </button>

      <button
          class="nav-register-button"
          @click="navigateToLogin"
      >
        Masz już konto? Zaloguj się
      </button>
    </div>
  </div>
</template>

<script>
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { useAuthStore } from '../../store/auth'
import './Register.css'

export default {
  name: 'Register',
  setup() {
    const router = useRouter()
    const authStore = useAuthStore()

    const username = ref('')
    const email = ref('')
    const password = ref('')
    const confirmPassword = ref('')
    const error = ref('')
    const loading = ref(false)

    const handleRegister = async () => {
      if (!username.value || !email.value || !password.value || !confirmPassword.value) {
        error.value = 'Proszę wypełnić wszystkie pola'
        return
      }

      if (password.value !== confirmPassword.value) {
        error.value = 'Hasła nie są zgodne'
        return
      }

      loading.value = true
      try {
        await authStore.register(username.value, email.value, password.value)
        router.push('/login')
      } catch (err) {
        error.value = err.response?.data?.message || 'Błąd rejestracji'
      } finally {
        loading.value = false
      }
    }

    const navigateToLogin = () => {
      router.push('/login')
    }

    return {
      username,
      email,
      password,
      confirmPassword,
      error,
      loading,
      handleRegister,
      navigateToLogin
    }
  }
}
</script>

// frontend-react/src/pages/Register/Register.jsx
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../../context/AuthContext.jsx';
import './Register.css';

function Register() {
    const [username, setUsername] = useState('');
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');
    const [confirmPassword, setConfirmPassword] = useState('');
    const [error, setError] = useState('');
    const [loading, setLoading] = useState(false);
    const { register } = useAuth();
    const navigate = useNavigate();

    const handleRegister = async (e) => {
        e.preventDefault();

        if (!username || !email || !password || !confirmPassword) {
            setError('Proszę wypełnić wszystkie pola');
            return;
        }
        if (password !== confirmPassword) {
            setError('Hasła nie są identyczne');
            return;
        }

        if (password.length < 6) {
            setError('Hasło musi mieć co najmniej 6 znaków');
            return;
        }

        setLoading(true);
        try {
            await register(username, email, password);
            navigate('/login');
        } catch (err) {
            setError(err.response?.data?.message || 'Błąd rejestracji');
        } finally {
            setLoading(false);
        }
    };
    return (
        <div>
            <div className="register-container">
                <p className="join-word">Dołącz!</p>
                <p className="register-word">Zarejestruj się</p>
                {error && <div style={{ color: 'red', marginBottom: '10px' }}>{error}</div>}


                <p className="email-word">Nazwa użytkownika</p>
                <input
                    className="email-input-data"
                    type="text"
                    value={username}
                    onChange={(e) => setUsername(e.target.value)}
                />
                <p className="email-word">E-mail</p>
                <input
                    className="email-input-data"
                    type="email"
                    value={email}
                    onChange={(e) => setEmail(e.target.value)}
                />
                <p className="email-word">Hasło</p>
                <input
                    className="password-input-data"
                    type="password"
                    value={password}
                    onChange={(e) => setPassword(e.target.value)}
                />
                <p className="email-word">Powtórz hasło</p>
                <input
                    className="repeat-password-input-data"
                    type="password"
                    value={confirmPassword}
                    onChange={(e) => setConfirmPassword(e.target.value)}
                />
                <button
                    className="register-button"
                    onClick={handleRegister}
                    disabled={loading}
                >
                    {loading ? 'Rejestracja...' : 'Zarejestruj'}
                </button>

                <button
                    className="nav-register-button"
                    onClick={() => navigate('/login')}
                >
                    Masz już konto? Zaloguj się
                </button>


            </div>




        </div>
    );
}

export default Register;
