// frontend-react/src/pages/Main/Main.jsx
import React from 'react';
import './Main.css'
import Header from "../../components/Header/Header.jsx";
import Filter from "../../components/Main/Filter/Filter.jsx";
import OfferList from "../../components/Main/OfferList/OfferList.jsx";

function Main() {

    return (
        <div>
            <Header/>
            <div className="main-horizontal-container">
                <Filter/>
                <OfferList/>
            </div>


        </div>
    );
}

export default Main;

// frontend-vue/src/pages/main/Main.vue
<template>
  <div>
    <Header />
    <div class="main-horizontal-container">

    </div>
  </div>
</template>

<script>
import Header from "../../components/Header/Header.vue";

export default {
  name: 'Main',
  components: {
    Header

  }
}
</script>

<style scoped>
.main-horizontal-container {
  display: flex;
  flex-direction: row;
  margin: 20px auto;
  width: 100%;
}
</style>
