// frontend-vue/src/pages/Offer/Offer.vue
<script setup>
import { ref, onMounted } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useAuthStore } from '../../store/auth'
import Header from '../../components/Header/Header.vue'
import VueFeather from 'vue-feather'
import { Carousel, Slide, Navigation } from 'vue3-carousel'
import 'vue3-carousel/dist/carousel.css'
import api from '../../services/api'
import './Offer.css'

const route = useRoute()
const router = useRouter()
const authStore = useAuthStore()
const offer = ref(null)

const fetchOffer = async () => {
  try {
    const response = await api.get(`/announcement/with-images/${route.params.id}`)
    offer.value = response.data
  } catch (err) {
    console.error('Błąd pobierania oferty:', err)
  }
}

const navigateToBook = () => {
  router.push(`/book/${offer.value.id}`)
}

onMounted(() => {
  fetchOffer()
})
</script>

<template>
  <div class="offer-page-container" v-if="offer">
    <Header />
    <div class="offer-horizontal-container">
      <div class="offer-vertical-container">
        <div class="offer-img-container">
          <Carousel :items-to-show="1" :wrap-around="false" :mouse-drag="true">
            <Slide v-for="(src, idx) in (offer.imageUrls || [])" :key="idx">
              <img
                  :src="src"
                  :alt="`Zdjęcie ${idx + 1}`"
                  class="offer-image"
              />
            </Slide>

            <template #addons>
              <Navigation />
            </template>
          </Carousel>
        </div>

        <div class="offer-description-container">
          <div class="offer-horizontal-container">
            <vue-feather type="search" class="loupe-icon" size="32"></vue-feather>
            <p class="offer-description-title">Opis</p>
          </div>
          <p class="offer-description-text">
            {{ offer.description }}
          </p>
        </div>
      </div>

      <div class="offer-panel-container">
        <p class="offer-panel-title">{{ offer.name }}</p>
        <p class="offer-panel-price">
          {{ offer.price ? `${offer.price.toLocaleString()} PLN` : 'Cena nie podana' }}
        </p>

        <div class="offer-buy-button" @click="navigateToBook">
          <vue-feather type="credit-card" class="buy-icon" size="43"></vue-feather>
        </div>
        <div class="offer-contact-button">
          <vue-feather type="phone" class="contact-icon" size="40"></vue-feather>
        </div>

        <div class="offer-information-container">
          <p class="offer-information-title">Informacje</p>
          <p class="offer-information-text">
            <span v-if="offer.vehicle?.productionYear">* {{ offer.vehicle.productionYear }}<br/></span>
            <span v-if="offer.vehicle?.mileage">* {{ offer.vehicle.mileage.toLocaleString() }} km<br/></span>
            <span v-if="offer.vehicle?.fuelType">* {{ offer.vehicle.fuelType }}<br/></span>
            <span v-if="offer.vehicle?.engineCapacity">* {{ offer.vehicle.engineCapacity }} cm³<br/></span>
            <span v-if="offer.vehicle?.power">* {{ offer.vehicle.power }} KM<br/></span>
          </p>
        </div>
      </div>
    </div>
  </div>
  <div v-else>Ładowanie oferty...</div>
</template>

// frontend-react/src/pages/Offer/Offer.jsx
import React, { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import './Offer.css';
import Header from "../../components/Header/Header.jsx";
import { Carousel } from "antd";
import { LuWalletMinimal } from "react-icons/lu";
import { HiDevicePhoneMobile } from "react-icons/hi2";
import { PiMagnifyingGlassBold } from "react-icons/pi";
import { useAuth } from '../../context/AuthContext';

function Offer() {
    const { id } = useParams();
    const { api } = useAuth();
    const [offer, setOffer] = useState(null);

    useEffect(() => {
        const fetchOffer = async () => {
            try {
                const response = await api.get(`/announcement/with-images/${id}`);
                setOffer(response.data);
            } catch (err) {
                console.error('Błąd pobierania oferty:', err);
            }
        };

        fetchOffer();
    }, [api, id]);

    if (!offer) return <div>Ładowanie oferty...</div>;

    return (
        <div className="offer-page-container">
            <Header />
            <div className="offer-horizontal-container">
                <div className="offer-vertical-container">
                    <div className="offer-img-container">
                        <Carousel arrows infinite={false}>
                            {(offer.imageUrls || []).map((src, idx) => (
                                <div key={idx}>
                                    <img
                                        src={src}
                                        alt={`Zdjęcie ${idx + 1}`}
                                        className="offer-image"
                                    />
                                </div>
                            ))}
                        </Carousel>
                    </div>

                    <div className="offer-description-container">
                        <div className="offer-horizontal-container">
                            <PiMagnifyingGlassBold className="loupe-icon" />
                            <p className="offer-description-title">Opis</p>
                        </div>
                        <p className="offer-description-text">
                            {offer.description}
                        </p>
                    </div>
                </div>

                <div className="offer-panel-container">
                    <p className="offer-panel-title">{offer.name}</p>
                    <p className="offer-panel-price">
                        {offer.price ? `${offer.price.toLocaleString()} PLN` : 'Cena nie podana'}
                    </p>

                    <div className="offer-buy-button">
                        <LuWalletMinimal className="buy-icon"/>
                    </div>
                    <div className="offer-contact-button">
                        <HiDevicePhoneMobile className="contact-icon"/>
                    </div>

                    <div className="offer-information-container">
                        <p className="offer-information-title">Informacje</p>
                        <p className="offer-information-text">
                            {offer.vehicle?.productionYear && <>* {offer.vehicle.productionYear}<br/></>}
                            {offer.vehicle?.mileage && <>* {offer.vehicle.mileage.toLocaleString()} km<br/></>}
                            {offer.vehicle?.fuelType && <>* {offer.vehicle.fuelType}<br/></>}
                            {offer.vehicle?.engineCapacity && <>* {offer.vehicle.engineCapacity} cm³<br/></>}
                            {offer.vehicle?.power && <>* {offer.vehicle.power} KM<br/></>}
                        </p>
                    </div>

                </div>
            </div>
        </div>
    );
}

export default Offer;
